### ISSUE TITLE
Hermes Lite 2.0 no longer works

### ISSUE THREAD

**Issue by sanamon** [g0orx/linhpsdr#31]
Hi, 

I have a Hermes lite 2.0 radio and use LinHPSDR, I noticed that a fresh checkout no longer works with the hermes lite 2.  
My "old" version which has commits up til "Date:   Sun Mar 10 13:46:18 2019 +0000" works, but somewhere among the last 6 commits something broke it.   If I try reverting the 2 last commits it works again, so i'm guessing something in the "improved control for LimeSDR" 
 6675f954b99c9ae59b0e7cca3510196e0bafa701 breaks Hermes Lite 2.0 support?

The old version doesn't work flawlessly as reception doesnt start when starting the radio, but changing the the sample rate from 48 to 96k or vice versa starts it.  So that does work, but with a recent clone it doesnt work at all, even after changing sample rate.

Best Regards,
Jonas

**Comment by radi8** [comment]
It is the same in my case also. John is getting a loan of an HL2 and I am sure he will fix this when it arrives. The issue of needing to change the sample rate to start the radio has been discussed in the hl groups forum some months ago.

73 Graeme zl2apv

**Comment by radi8** [comment]
Hi Jonas,

You can find the thread here
https://groups.google.com/forum/m/?fromgroups#!topic/hermes-lite/YoC05NCDnOs

73, Graeme ZL2APV

**Comment by sanamon** [comment]
Thanks Graeme!

Good to see i'm not the only one who has to change sample rate to start it. 

Can You also confirm that commit 6675f95 breaks Hermes Lite 2.0 support? 
(after this commit,  it doesn't help to change sample rate. It does not start at all)

Regards,
Jonas

**Comment by radi8** [comment]
Hello Jonas,

Yes that is correct and I needed to go back 1 version. I am sure that John will fix this when he gets his HL2. It's pretty amazing that it has got as far as it has considering that he was flying blind.

73, Graeme ZL2APV

**Comment by sanamon** [comment]
Yes, i agree. Kudos for making such a great software also!

Regards, 
Jonas

**Comment by g0orx** [comment]
I have pushed an update mainly for SoapySDR and support for QO-100 transverter settings.   I have also run this version of the code with a RadioBerry that emulates a Hermes Lite 2.  Can someone check if this is working with  a real Hermes Lite 2.0?

Thanks,

-- John g0orx/n6lyt

**Comment by sanamon** [comment]
Hi John,

Thanks for the update. Unfortunately I still get only a back
scope/waterfall and changing the sample rate does not start it.

Best Regards,
Jonas


Den tis 23 apr. 2019 kl 23:17 skrev John Melton <notifications@github.com>:

**Comment by radi8** [comment]
Hello John et al,

Sorry but moved house today, no Internet, just my cell phone for a few days. Will test as soon as I can.

73, Graeme zl2apv

**Comment by g0orx** [comment]
I will be going to see Alan Hopper tomorrow to test with his Hermes Lite 2.
I will take my Radioberry so we can try to work out why one works and the
other does not.

-- John

**Comment by g0orx** [comment]
Fixed.  Hermes Lite added a timeout on receiving data from the application.  At startup this was being exceeded after sending start to radio but before application ready to process data.

**Comment by sanamon** [comment]
Thanks John, 

I just did a git pull and tested, but now it segfaults after starting the radio...

Build: 2019-04-25 Beta
GTK+ version 3.22.30
sysname: Linux
nodename: sanamon-ThinkPad-X220
release: 4.15.0-47-generic
version: #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
machine: x86_64
discovery
protocol1_discovery
discover: looking for HPSDR devices on lo
discover: bound to lo
discover_receive_thread
discovery: bytes read -1
discovery: recvfrom socket failed for discover_receive_thread: Resursen tillfälligt otillgänglig
discovery: exiting discover_receive_thread
discover: exiting discover for lo
discover: looking for HPSDR devices on wlp3s0
discover: bound to wlp3s0
discover_receive_thread
discovered: received 60 bytes
discovery: found device=6 software_version=62 status=2 address=10.0.10.61 (00:1C:C0:A2:13:DD) on wlp3s0
discovery: bytes read -1
discovery: recvfrom socket failed for discover_receive_thread: Resursen tillfälligt otillgänglig
discovery: exiting discover_receive_thread
discover: exiting discover for wlp3s0
discovery found 1 devices
discovery: found device=6 software_version=62 status=2 address=10.0.10.61 (00:1C:C0:A2:13:DD) on wlp3s0
protocol2_discover: looking for HPSDR devices on wlp3s0
protocol2_discover: bound to wlp3s0 10.0.10.83 255.255.255.0
protocol2_disovery: thread_id=0x55ef7218c1e0
protocol2_discover: bytes read -1
protocol2_discover: recvfrom socket failed for discover_receive_thread: Resursen tillfälligt otillgänglig
protocol2_discover: exiting protocol2_discover_receive_thread
protocol2_discover: exiting discover for wlp3s0
protocol2_discovery found 1 devices
discovery: found protocol=0 device=6 software_version=62 status=2 address=10.0.10.61 (00:1C:C0:A2:13:DD) on wlp3s0
main: discovery found 1 devices
discovered: 0 device=6
adding Hermes Lite
tree_selection_changed_cb
tree_selection_changed_cb: selected=Hermes Lite,1,6.2,10.0.10.61,00:1C:C0:A2:13:DD
tree_selection_changed_cb: first=Hermes Lite,1,6.2,10.0.10.61,00:1C:C0:A2:13:DD
found 0
starting Linux HPSDR (Beta): Hermes Lite P1 v6.2 10.0.10.61 (00:1C:C0:A2:13:DD) on wlp3s0
create_radio for Hermes Lite 6
loadProperties: /home/sanamon/.local/share/linhpsdr/00-1C-C0-A2-13-DD.props
create_receiver: channel=0 sample_rate=48000
create_receiver: channel=0 frequency_min=0 frequency_max=30720000
create_receiver: buffer_size=1024
create_receiver: fft_size=2048
create_receiver: OpenChannel: channel=0 buffer_size=1024 sample_rate=48000 fft_size=2048 output_samples=1024
receiver_init_analyzer: channel=0 zoom=1 pixels=0 pixel_samples=(nil)
receiver_update_title: Linux HPSDR: Rx-0 ADC-0 48000
create_vfo: rx=0
receiver_configure_event: gtk_paned_set_position: rx=0 position=30 height=120 percent=0,253638
audio_open_output: alsa_output.pci-0000_00_1b.0.analog-stereo
audio_open_output: allocated local_audio_buffer 0x55ef7488b640 size 32768 bytes
create_transmitter: channel=8
transmitter_init_analyzer: width=0 pixels=0
update_timer: fps=10
Segmenteringsfel (minnesutskrift skapad)

**Comment by sanamon** [comment]
Never mind. 
Did a "make clean" and a new "make" and it works!
Thanks again!

Regards,
Jonas
